### ISSUE TITLE
Roadmap v0.1.0

### ISSUE THREAD

**Issue by abrondijk** [smartknob-ha/firmware#48]
### Hardware interfaces

The following components need to be created before the "software" side of tings can be realized

- [x] https://github.com/smartknob-ha/firmware/issues/32
- [x] https://github.com/smartknob-ha/firmware/issues/36
- [ ] https://github.com/smartknob-ha/firmware/issues/39
- [x] https://github.com/smartknob-ha/firmware/issues/56
- [ ] https://github.com/smartknob-ha/firmware/issues/29

### Software interfaces

- [ ] smartknob-ha/firmware#52
- [ ] smartknob-ha/firmware#54
- [ ] smartknob-ha/firmware#53
- [ ] smartknob-ha/firmware#51
- [ ] smartknob-ha/firmware#50
- [ ] smartknob-ha/firmware#49

### Main control loop

Ultimately all the above interfaces/components need to be tied together.

- [ ] Main Control Loop
